### ISSUE TITLE
Errors using ZK springboard

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-SpringBoard/SpringBoard-Core#112]
Many errors in this infolog: [infolog.txt](https://github.com/Spring-SpringBoard/SpringBoard-Core/files/954445/infolog.txt)

Other issues:
 * Music was playing.
 * The top right tab is hidden underneath the chobby menu button.
 * The terrain is red.
 * I don't know how do make anything happen. Unit placement seems impossible. Map manipulation seems impossible.
 * There is no console output.
 * There are two console inputs, one is blue and floats near the middle of the screen.

**Comment by gajop** [comment]
OK, after a few fixes here and in the https://github.com/Spring-SpringBoard/SpringBoard-ZK repo (which I managed to minimize now), it seems to load properly at least!

Regarding your issues:
- Don't see an issue with music playing? Should it not? ×
- Unfortunately SB<->Game draws on top of each other. Rather than trying to figure out where games put there stuff, I want to limit game's Screen0 screen to a fixed size (that's WIP though). ×
- Terrain isn't red for me. ✓
- Unit and map editing works now. ✓
- I have text output at the bottom. Isn't that ZK default? Should there be something else? ✓
- Chonsole (one shipped with SB) input seems to work, while the other one (ZK/engine one is hidden for me). ✓

**Comment by GoogleFrog** [comment]
Point two is SB <-> Chobby. Ideally SB would implement ingame lobby switch handling. This tells chobby that the launched game is dealing with the ingame UI and that chobby should not be the one to draw the button.

**Comment by gajop** [comment]
How does SB specify that?

**Comment by GoogleFrog** [comment]
Spring.SendLuaMenuMsg("disableLobbyButton") tells chobby that the game will take over handling of the menu button. https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaUI/Widgets/gui_epicmenu.lua#L2157

Spring.SendLuaMenuMsg("showLobby") shows chobby. https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaUI/Widgets/gui_epicmenu.lua#L3137

**Comment by gajop** [comment]
SB integrated with Chobby with https://github.com/Spring-SpringBoard/SpringBoard-Core/commit/f09c4b03cd1da0bc67c10a34ff8c2d533a5f3538 . Split the discussion about how game UI should be handled to https://github.com/Spring-SpringBoard/SpringBoard-Core/issues/197 -> closing this issue.
